---
application:
  name: "persons"
  project: "sabyapp"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 8080
databases:
- type: "MONGODB"
  name: "datastore"
  version: "4.4"
routers:
- name: "main-persons"
  routes:
  - application_name: "persons"
    paths:
    - "/*"
