---
application:
  name: "myserver"
  project: "sabyapp"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "testdb"
  version: "4.4"
routers:
- name: "main-myserver"
  routes:
  - application_name: "myserver"
    paths:
    - "/*"
