---
application:
  name: "myserver"
  project: "sabyApp"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "datastore"
  version: "4.4"
routers:
- name: "main-myserver"
  routes:
  - application_name: "myserver"
    paths:
    - "/*"
