version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080 # host:container
    volumes:
      - .:/app

  mongodb:
    image: mongo
    ports:
      - "2717:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1

volumes:
  mongodata:

networks:
  network1: