version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "2717:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1

volumes:
  mongodata:

networks:
  network1: